### ISSUE TITLE
 PermissionError: [Errno 13] Permission denied: '/config/settings.cfg'

### ISSUE THREAD

**Issue by tylerk4** [ipsingh06/seedsync#137]
Running seedsync in a Docker container.

Docker-compose as follows (partially redacted):

```
version: '3.8'

services:  
  seedsync:
    image: ipsingh06/seedsync:latest
    container_name: seedsync
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/seedsync/data:/config
      - /mnt/media/:/downloads
      - /mnt/backup:/backup/
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=000
      - TZ=XXXXX
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.seedsync.entrypoints=http"
      - "traefik.http.routers.seedsync.rule=Host(`seedsync.XXXX.XXXXXX.net`)"
      - "traefik.http.middlewares.seedsync-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.seedsync.middlewares=seedsync-https-redirect"
      - "traefik.http.routers.seedsync-secure.entrypoints=https"
      - "traefik.http.routers.seedsync-secure.rule=Host(`seedsync.XXXX.XXXX.net`)"
      - "traefik.http.routers.seedsync-secure.tls=true"
      - "traefik.http.routers.seedsync-secure.service=seedsync"
      - "traefik.http.services.seedsync.loadbalancer.server.port=8800"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
```

When running docker compose up, the following error is shown:

```
[+] Running 1/0
 ✔ Container seedsync  Recreated                                                                                                                                                                                     0.0s
Attaching to seedsync
seedsync  | Traceback (most recent call last):
seedsync  |   File "/app/python/seedsync.py", line 378, in <module>
seedsync  |     seedsync = Seedsync()
seedsync  |   File "/app/python/seedsync.py", line 60, in __init__
seedsync  |     config.to_file(self.config_path)
seedsync  |   File "/app/python/common/persist.py", line 53, in to_file
seedsync  |     with open(file_path, "w") as f:
seedsync  | PermissionError: [Errno 13] Permission denied: '/config/settings.cfg'
seedsync  |
seedsync  | During handling of the above exception, another exception occurred:
seedsync  |
seedsync  | Traceback (most recent call last):
seedsync  |   File "/app/python/seedsync.py", line 386, in <module>
seedsync  |     Seedsync.logger.exception("Caught exception")
seedsync  | AttributeError: 'NoneType' object has no attribute 'exception'
seedsync exited with code 0
```
